import OnboardingKit
import SwiftUI

public struct OnboardingView: View {
    @State private var currentPage: Int = 0
    private let pages = ["Welcome To Open Space: Land On A Planet Or Navigate To A Space Object", "Collect Minerals And View Them", "Create Objects In Your Sphere Using Minerals", "Earn In Game Cash Each Day Generated By Objects and Spheres You've Created", "Get To The Top Of The Galactic Leaderboard"]
    private let onFinish: () -> Void

    public init(onFinish: @escaping () -> Void) {
        self.onFinish = onFinish
    }

    private var imageName: String {
        switch currentPage {
        case 0:
            return "landornavigate"
        case 1:
            return "claimminerals"
        case 2:
            return "replicator"
        case 3:
            return "earnminerals"
        case 4:
            return "leaderboard"
        default:
            return "default_image" // Provide a default image name
        }
    }

    public var body: some View {
        VStack {
            Text(pages[currentPage])
                .font(.largeTitle)
                .padding()

            Image(imageName)
                .resizable()
                .scaledToFit()
                .frame(width: 200, height: 200)
                .foregroundColor(.yellow)
                .padding()
                .onAppear {
                    print("Image view appeared")
                    print("Displaying image: \(imageName)")
                }

            Text("Tap Next To Continue")
                .multilineTextAlignment(.center)
                .padding()

            Button(action: {
                if currentPage < pages.count - 1 {
                    currentPage += 1
                } else {
                    onFinish()
                }
            }) {
                Text(currentPage < pages.count - 1 ? "Next" : "Finish")
                    .padding()
                    .background(Color.blue)
                    .foregroundColor(.white)
                    .cornerRadius(10)
            }
            .padding()
        }
    }
}
